### ISSUE TITLE
CB4 vs CB5 incompatibility for getModulesRoutingTable()

### ISSUE THREAD

**Issue by gpickin** [coldbox-modules/route-visualizer#5]
CB4 has getModulesRoutingTable()
CB5 has accessors for the moduleRoutingTable variable so its getModuleRoutingTable()

Its not compatible.
We probably have to add a wrapper function into CB5's router file to make this work.
I'll make the change here, and add it to ColdBox as well.

**Comment by gpickin** [comment]
https://github.com/coldbox-modules/route-visualizer/pull/6

**Comment by lmajano** [comment]
Solved
